print("bem-vindo a TABO, seu app de taboada para preguiçosos, favorita!")
tabunumber = int(input("Digite um número e saiba sua tabuada:"))
print (f"A tabuada é: {tabunumber} x 0 = {tabunumber * 0}")
print (f"A tabuada é: {tabunumber} x 0 = {tabunumber * 1}")
print (f"A tabuada é: {tabunumber} x 0 = {tabunumber * 2}")
print (f"A tabuada é: {tabunumber} x 0 = {tabunumber * 3}")
print (f"A tabuada é: {tabunumber} x 0 = {tabunumber * 4}")
print (f"A tabuada é: {tabunumber} x 0 = {tabunumber * 5}")
print (f"A tabuada é: {tabunumber} x 0 = {tabunumber * 6}")
print (f"A tabuada é: {tabunumber} x 0 = {tabunumber * 7}")
print (f"A tabuada é: {tabunumber} x 0 = {tabunumber * 8}")
print (f"A tabuada é: {tabunumber} x 0 = {tabunumber * 9}")
print (f"A tabuada é: {tabunumber} x 0 = {tabunumber * 10}")
